services:
  - type: web
    name: community-hub-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: VITE_API_URL
        value: https://communityhub-09ib.onrender.com/api