services:
  - type: web
    name: community-hub-frontend
    runtime: static
    buildCommand: echo "Skipping build - using pre-built files"
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value:https://communityhub-09ib.onrender.com