package handlers

import (
    "communityHub/internal/auth"
    "communityHub/internal/models"
    "communityHub/internal/repository"
    "net/http"
    "os" // <-- ADDED for production detection

    "github.com/gin-gonic/gin"
    "github.com/google/uuid"
    "golang.org/x/crypto/bcrypt"
)

type AuthHandler struct {
    userRepo *repository.UserRepository
}

func NewAuthHandler(userRepo *repository.UserRepository) *AuthHandler {
    return &AuthHandler{userRepo: userRepo}
}

// Helper function to check if running in production
func isProduction() bool {
    return os.Getenv("GO_ENV") == "production" || os.Getenv("RENDER") != ""
}

func (h *AuthHandler) Register(c *gin.Context) {
    var req models.RegisterRequest
    if err := c.ShouldBindJSON(&req); err != nil {
        c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
        return
    }

    // Validate input
    if req.Username == "" || req.Email == "" || req.Password == "" {
        c.JSON(http.StatusBadRequest, gin.H{"error": "all fields are required"})
        return
    }

    // Check if user exists by email
    existingUser, err := h.userRepo.FindByEmail(req.Email)
    if err != nil {
        c.JSON(http.StatusInternalServerError, gin.H{"error": "database error"})
        return
    }
    if existingUser != nil {
        c.JSON(http.StatusConflict, gin.H{"error": "email already exists"})
        return
    }

    // Check if user exists by username
    existingUser, err = h.userRepo.FindByUsername(req.Username)
    if err != nil {
        c.JSON(http.StatusInternalServerError, gin.H{"error": "database error"})
        return
    }
    if existingUser != nil {
        c.JSON(http.StatusConflict, gin.H{"error": "username already exists"})
        return
    }

    // Hash password
    hashedPassword, err := auth.HashPassword(req.Password)
    if err != nil {
        c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to hash password"})
        return
    }

    // Create user - ID will be generated by BeforeCreate hook
    user := &models.User{
        Username: req.Username,
        Email:    req.Email,
        Password: hashedPassword,
        Role:     "user",
    }

    if err := h.userRepo.Create(user); err != nil {
        c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to create user"})
        return
    }

    // Generate token
    token, err := auth.GenerateToken(user.ID.String(), user.Username, user.Email)
    if err != nil {
        c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to generate token"})
        return
    }

    // Set cookie with production-ready settings
    c.SetCookie(
        "auth_token",
        token,
        3600*24, // 24 hours
        "/",     // path - available on all routes
        "",      // domain - empty works best for Render
        isProduction(), // secure - true for HTTPS, false for local
        true,    // httpOnly - prevents XSS attacks
    )

    c.JSON(http.StatusCreated, gin.H{
        "message": "user created successfully",
        "user": gin.H{
            "id":       user.ID,
            "username": user.Username,
            "email":    user.Email,
        },
    })
}

func (h *AuthHandler) Login(c *gin.Context) {
    var req models.LoginRequest
    if err := c.ShouldBindJSON(&req); err != nil {
        c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
        return
    }

    // Validate input
    if req.Email == "" || req.Password == "" {
        c.JSON(http.StatusBadRequest, gin.H{"error": "email and password are required"})
        return
    }

    // Find user by email
    user, err := h.userRepo.FindByEmail(req.Email)
    if err != nil {
        c.JSON(http.StatusInternalServerError, gin.H{"error": "database error"})
        return
    }
    if user == nil {
        c.JSON(http.StatusUnauthorized, gin.H{"error": "invalid credentials"})
        return
    }

    // Check password
    if err := bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(req.Password)); err != nil {
        c.JSON(http.StatusUnauthorized, gin.H{"error": "invalid credentials"})
        return
    }

    // Generate token
    token, err := auth.GenerateToken(user.ID.String(), user.Username, user.Email)
    if err != nil {
        c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to generate token"})
        return
    }

    // Set cookie with production-ready settings
    c.SetCookie(
        "auth_token",
        token,
        3600*24, // 24 hours
        "/",     // path - available on all routes
        "",      // domain - empty works best for Render
        isProduction(), // secure - true for HTTPS, false for local
        true,    // httpOnly - prevents XSS attacks
    )

    c.JSON(http.StatusOK, gin.H{
        "message": "login successful",
        "user": gin.H{
            "id":       user.ID,
            "username": user.Username,
            "email":    user.Email,
        },
    })
}

func (h *AuthHandler) Logout(c *gin.Context) {
    // Clear the auth cookie with production-ready settings
    c.SetCookie(
        "auth_token",
        "",
        -1, // negative value deletes the cookie
        "/",
        "",
        isProduction(),
        true,
    )

    c.JSON(http.StatusOK, gin.H{"message": "logout successful"})
}

func (h *AuthHandler) GetCurrentUser(c *gin.Context) {
    userID := c.GetString("userID")
    if userID == "" {
        c.JSON(http.StatusUnauthorized, gin.H{"error": "not authenticated"})
        return
    }

    // Parse UUID
    uid, err := uuid.Parse(userID)
    if err != nil {
        c.JSON(http.StatusInternalServerError, gin.H{"error": "invalid user ID"})
        return
    }

    user, err := h.userRepo.FindByID(uid)
    if err != nil {
        c.JSON(http.StatusInternalServerError, gin.H{"error": "database error"})
        return
    }
    if user == nil {
        c.JSON(http.StatusNotFound, gin.H{"error": "user not found"})
        return
    }

    c.JSON(http.StatusOK, gin.H{
        "user": gin.H{
            "id":       user.ID,
            "username": user.Username,
            "email":    user.Email,
            "bio":      user.Bio,
            "avatar":   user.Avatar,
            "role":     user.Role,
        },
    })
}